spec:
  replicas: 1
  template:
    spec:
      containers:
        - 
          resources:
            requests:
              cpu: 
              memory: 
            limits:
              cpu: 
              memory: 512Mi
          env:
          - name: MYSQL_SERVICE_NAME
            value: mysql
          - name: MYSQL_SERVICE_DATABASE
            value: sampledb
          - name: MYSQL_SERVICE_USERNAME
            value: ${mysql-service-username}
          - name: MYSQL_SERVICE_PASSWORD
            value: ${mysql-service-password}
          - name: JAVA_DIAGNOSTICS
            value: true
